### ISSUE TITLE
Dataspace Connector UI connection ERROR

### ISSUE THREAD

**Issue by itachiliu** [International-Data-Spaces-Association/DataspaceConnectorUI#313]
Hello， I installed the dataspace connector and the dataspace connectorUI as instructed. Here's how:

dataspace connector：
`docker run -p 8080:8080 --name connector ghcr.io/international-data-spaces-association/dataspace-connector:latest`

dataspace connectorUI：
```
sudo docker build -t dataspace-connector-ui .
sudo docker-compose up
```
and the docker build hint：
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it
npm WARN backend@1.0.1 No description
npm WARN backend@1.0.1 No repository field.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

but it build and execute successfully.

![image](https://github.com/International-Data-Spaces-Association/DataspaceConnectorUI/assets/22728196/948c8508-52e9-4786-8b67-0cd3cd9218ed)

Next step, I access the localhost:8083, there are some error int the website:
![image](https://github.com/International-Data-Spaces-Association/DataspaceConnectorUI/assets/22728196/6aa00af1-8702-46c5-8eb1-fde5906eb73b)

the log show :
![image](https://github.com/International-Data-Spaces-Association/DataspaceConnectorUI/assets/22728196/b0222566-6499-4f14-834e-5fbf383e29c6)

Then I access 'https://admin:password@localhost:8080/api/configurations' by website, it succeed.
![image](https://github.com/International-Data-Spaces-Association/DataspaceConnectorUI/assets/22728196/e780c1c4-8665-4ade-8713-32c565a0526f)

Error: connect ECONNREFUSED 127.0.0.1:8080

So, what's wrong with my option and how to solve it，can you help me? 

Thanks.

**Comment by jdortega** [comment]
I have the same issue. I have configured a DSC and its UI using docker. I can access the connector API Swagger UI and try many of the request that the UI is giving error. 

In the UI I get the same error: Error: connect ECONNREFUSED 127.0.0.1:8080

I have checked the port of the connector is correct.

**Comment by mitsos-tsali** [comment]
heya fellas, anyone managed to solve this error? 

i tried changing "username" to "key" and "password" to "value"  in the authentication headers, as an old issue suggested, but still no improvement. 

thanks again!

**Comment by jungyitsai** [comment]
I used this docker-compose.yml to solve this problem.

Change `CONNECTOR_URL=https://localhost:8080` to `CONNECTOR_URL=https://dc:8080`

Because `CONNECTOR_URL=https://localhost:8080` will access to dataspace-connector-ui self.

```
version: '3.5'

services:
    dataspace-connector:
        container_name: "dc"
        image: ghcr.io/international-data-spaces-association/dataspace-connector:latest
        ports:
            - "8080:8080"
    dataspace-connector-ui:
        container_name: "dci"
        image: ghcr.io/international-data-spaces-association/dataspace-connector-ui:sha-1d4426a
        environment:
            - CONNECTOR_URL=https://dc:8080
            - CONNECTOR_USER=admin
            - CONNECTOR_PASSWORD=password
        ports:
            - "8083:8083"
```
