### ISSUE TITLE
Problems with 8.3.0 deployment

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/DataspaceConnectorUI#91]
Hi,
I have the following working config for version 8.1.0 of the UI
```
  connector:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:6.0.0
    restart: unless-stopped
    environment:
      - SERVER_PORT=8080
      - SERVER_SSL_ENABLED=false
    networks:
      - test
    ports:
      - 8085:8080

  ui:
    image: ghcr.io/international-data-spaces-association/dataspace-connector-ui:8.1.0
    restart: always
    ports:
      - 8088:8082
      - 8087:8083
    environment:
      - CONNECTOR_URL=http://connector:8080
      - UI_BACKEND_URL=http://localhost:8087
      - UI_TITLE=Dataspace Connector UI
    networks:
      - test
```
Now, with version 8.3.0 of the UI, I changed the UI part of my docker-compose.yml to this:
```
  ui:
    image: ghcr.io/international-data-spaces-association/dataspace-connector-ui:8.1.0
    restart: always
    ports:
      - 8087:8083
    environment:
      - CONNECTOR_URL=http://connector:8080
      - UI_TITLE=Dataspace Connector UI
    networks:
      - test
```
And I'm getting a "Get connector settings failed" error message in the UI. When opening a console in the browser, I can see that the frontend is trying to connect to localhost:8083 and not to 8087. How can this be fixed? Adding the UI_BACKEND_URL as with version 8.1.0 does not seem to work anymore.
